config/routes.rb
Rails.application.routes.draw do
  # get 'index/new'
  # get 'index/create'
  # get 'index/show'
  # get 'index/destroy'
  devise_for :users
  root to: "bikes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/checkout", to: "bookings#checkout"

  resources :bikes do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :delete_all
  has_many :reviews
  validates :title, presence: true
  validates :bike_postcode2, presence: true
  validates :description, length: { minimum: 15 }
  TYPE = %w[Electric Road Mountain Folding Kids Hybrid City Trike]
  validates :bike_type, inclusion: { in: TYPE }, presence: true
  validates :price, presence: true, numericality: { only_float: true }
  validates :photo, presence: true
  has_one_attached :photo
  geocoded_by :bike_postcode2
  after_validation :geocode, if: :will_save_change_to_bike_postcode2?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user
  has_many :bikes
  has_many :users
  has_one_attached :photo
  # validates :start_date, :end_date, presence: true
  # validates :start_date, comparison: { less_than: :end_date }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bike
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes
  has_many :bookings
  has_many :reviews
  # validates :first_name, :last_name, presence: true
  # validates :first_name, :last_name, format: { with "/^[a-z]+$/i" }
  # validates :postcode, format: { with "^[a-zA-Z0-9]*$",
  # message: "has to be a UK postcode"
  # }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @bikes = Bike.where(bike_type: params[:query])
    else
      @bikes = Bike.all
    end
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        marker_window_html: render_to_string(partial: "marker_window", locals: {bike: bike}),
        marker_icon_html: render_to_string(partial: "marker_icon", locals: {bike: bike})
      }
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to bike_path(@bike), notice: 'Bike post was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bike.update(bike_params)
      redirect_to bike_path(@bike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path, notice: 'Bike was successfully destroyed.'
    # redirect_to bikes_path, status: :see_other if @bike.destroy
  end

  private

  def bike_params
    params.require(:bike).permit(:title, :description, :bike_type, :price, :status, :photo, :query, :bike_postcode2)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_bike, only: %i[new create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = current_user
    if @booking.save!
      redirect_to bike_path(@bike), alert: "You successfully booked a bike!"
    else
      render :new
    end
  end

  def checkout
    @bookings = current_user.bookings
    @titles = @bookings.includes(:user).map { |booking| Bike.find(booking.bike_id).title }
  end

  def index
    @bookings = Booking.all
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_bike
    @bike = Bike.find(params[:bike_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @bike = Bike.find(params[:bike_id])
    @review = Review.new(review_params)
    @user = current_user
    @review.bike = @bike
    @review.user = @user
    if @review.save
      redirect_to bike_path(@bike)
    else
      render "bikes/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_marker_icon.html.erb
<div class="badge rounded-pill bg-primary fs-6">
  £<%= bike.price.to_i %>
</div>

app/views/bikes/_marker_window.html.erb
  <img src="<%= cloudinary_url(bike.photo.key) %>" class="card-img-top" alt="image">
  <h5 class="p-2"><%= bike.title %></h5>
  <div class="row p-2">
    <div class="col">
      <p style="font-size:18px">£<%= bike.price.to_i %> day</p>
      <a href="<%= bike_path(bike) %>" class="stretched-link"></a>
    </div>
  </div>

app/views/bikes/index.html.erb
<div class="container">
  <h1 class="my-5">Bikes in your area</h1>
  <div class="container m-4">
    <div class="container flex">
      <div class="row">
        <% bike_type = %w(Electric Road Mountain Folding Kids Hybrid City Trike All)%>
        <% bike_type.each do |type| %>
        <div class="col text-center">
          <% if type == 'All' %>
            <%= link_to type, bikes_path, class: "btn btn-primary mr-2" %>
          <% else %>
            <%= link_to type, bikes_path(query: type), class: "btn btn-light" %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
   </div>
   <div class="row row-cols-2 row-cols-lg-4 g-2 g-lg-3">
     <% @bikes.each do |bike| %>
       <div class="col-md-4">
         <div class="card">
          <% if cloudinary_url(bike.photo.key) %>
            <img src="<%= cloudinary_url(bike.photo.key) %>" class="card-img-top" alt="image">
          <% else %>
            <img src="https://www.bikehighway.com/media/catalog/product/cache/8dfd20b727bccb444e9ac19dde97c5ca/0/0/0002_balance_bike_-_mint_green_angled_1024x1024.jpg" class="card-img-top" alt="image">
          <% end %>
           <div class="card-body">
             <h5 class="card-title"><%= bike.title %></h5>
              <p class="d-inline-flex mb-3 px-2 py-1 fw-semibold text-success-emphasis bg-success-subtle border border-success-subtle rounded-2">
                <%= bike.bike_type %>
                </p>
             <p class="card-text">
                <br>
               <%= bike.description.truncate_words(25) %>
               <div class="row">
              <div class="col">
                <p class="card-text"><%= number_to_currency bike.price, unit: "£" %><p>
              </div>
            </div>
             </p>
             <div class="">
               <a href="<%= bike_path(bike) %>" class="btn btn-primary mr-2">View</a>
               <a href="<%= edit_bike_path(bike) %>" class="btn btn-secondary mr-2">Edit</a>
               <%# <%= link_to "Delete", bike_path(bike), method: :destroy, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
             </div>
           </div>
         </div>
       </div>
     <% end %>
   </div>
 </div>

 <br>

 <div class="text-center my-5">
   <%= link_to 'Add Bike', new_bike_path, class: "btn btn-primary" %>
 </div>

 <div data-controller='hello' data-hello-target='helloParagraph'>
  <p>Hello World!</p>
</div>

app/views/bikes/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="bike-form">
        <h1>Add a new Bike</h1>
        <div class="mt-3">
          <%= render "share/form" %>
        </div>
      </div>
      <%= link_to "Back to Bikes", bikes_path, class: "btn btn-secondary btn-sm" %>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="container py-4">
  <%= link_to "Back to Bikes", bikes_path, class: "btn btn-secondary btn-sm mb-3" %>
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <div class= "containter">
        <div class="row">
          <div class="col-md-4">
            <%= image_tag cl_image_path(@bike.photo.key, width: 500, height: 500, crop: :fill), class: "img-fluid", alt: "image" %>
          </div>
          <div class="col-md-8">
            <p class="d-inline-flex mb-3 px-2 py-1 fw-semibold text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-2"><%= @bike.bike_type %></p>
            <div class="row">
              <div class="col-9">
                <h1 class="display-5 fw-bold"><%= @bike.title %></h1>
              </div>
              <div class="col-3">
                <%rating_array = [] %>
                <% @bike.reviews.each do |review| %>
                <%rating_array << review.rating %>
                <% end %>
                <% if rating_array.length == 0 %>
                <p><button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#exampleModal">add a review</button></p>
                <% else %>
                <% total=rating_array.sum/rating_array.length %>
                <p><i class="bi bi-star-fill"></i> <%=total%><i class="bi bi-dot"></i><button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#exampleModal"><%=rating_array.length%> reviews</button></p>
                <%end%>
              </div>
            </div>
            <p class="fs-4"><%= @bike.description %></p>
            <p class="fs-4">London, <%= @bike.bike_postcode2 %></p>
            <p class="fs-4">Price: £<%= @bike.price.to_i %></p>
            <div class="container mt-4">
              <div class="row">
                <div class="col-6 m-auto">
                  <div class="bike-form">
                    <h1>Select a date</h1>
                    <div class="mt-3">
                      <div class="container mt-4">
                        <div class="row mt-4">
                          <%= render "share/flatpickr", bike: @bike, booking: @booking %>
                                      <%= button_to 'Delete', bike_path(@bike), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-secondary' %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
          <% if alert %>
          <div class="flash flash-success alert-center card-slide-up card-bounce" role="alert">
            <span><strong>Yay!</strong> 🎉 <%= alert %></span>
            <a data-bs-dismiss="alert" aria-label="Close">
            </a>
          </div>
          <% end %>
          <script>
            document.addEventListener("DOMContentLoaded", function() {
              const cardElement = document.querySelector(".card");
              cardElement.classList.add("card-slide-up");
            });
          </script>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title d-flex justify-content-center" id="exampleModalLabel"><p><i class="bi bi-star-fill"></i> <%=total%><i class="bi bi-dot"></i><%=rating_array.length%> reviews</button></p></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          <% @bike.reviews.each do |review| %>
            <li class="list-group-item">
            <small>
            <% count = 0 %>
            <% 5.times do %>
            <% if review.rating > count %>
              <i class="fa-solid fa-star"></i>
            <% else %>
              <i class="fa-regular fa-star"></i>
            <% end %>
              <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
            <%# <p><%= @user.user_id %>
            </li>
          <% end %>
        </div>
      </div>
      <div class="modal-footer d-flex align-items-center justify-content-center">
        <%= simple_form_for [@bike, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content %>
        <%= f.submit "Add your review", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bikes/update.html.erb
<h1>Update Bike</h1>
<%= link_to "Back to Bikes", bikes_path, class: "btn btn-secondary btn-sm mb-3" %>

app/views/bookings/checkout.html.erb
<h1>Booked Bikes</h1>

<% if @titles.present? %>
  <ul>
    <% @titles.each do |title| %>
      <li><%= title %></li>
    <% end %>
  </ul>
<% else %>
  <p>No bookings found for this bike.</p>
<% end %>

<%= link_to "Back to Bikes", bikes_path, class: "btn btn-secondary btn-sm" %>
<%= link_to "Checkout", checkout_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bkr Bike</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
   <%= render "share/navbar" %>
    <%# <p class="notice"><%= notice </p>%>
    <%# <p class="alert"><%= alert </p>%>
    <%= yield %>
    <%= render "share/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/share/_card.html.erb
<% @bikes.each do |bike| %>
<div class="col-md-3">
  <div class="card">
    <a href="<%= bike_path(bike) %>" class="stretched-link"></a>
    <% if cloudinary_url(bike.photo.key) %>
    <img src="<%= cloudinary_url(bike.photo.key) %>" class="card-img-top" alt="image">
    <% else %>
    <img src="https://www.bikehighway.com/media/catalog/product/cache/8dfd20b727bccb444e9ac19dde97c5ca/0/0/0002_balance_bike_-_mint_green_angled_1024x1024.jpg" class="card-img-top" alt="image">
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= bike.title %></h5>
      <p class="d-inline-flex mb-3 px-2 py-1 fw-semibold text-success-emphasis bg-success-subtle border border-success-subtle rounded-2">
        <%= bike.bike_type %>
      </p>
      <p class="card-text">
        <br>
        <%= bike.description %>
      <div class="row">
        <div class="col-6">
          <p class="card-text"><%= number_to_currency bike.price, unit: "£" %></p>
        </div>
        <div class="col-6">
          <%rating_array = [] %>
          <% bike.reviews.each do |review| %>
          <%rating_array << review.rating %>
          <% end %>
          <% if rating_array.length >0 %>
          <% total=rating_array.sum/rating_array.length %>
          <p><i class="bi bi-star-fill"></i> <%=total%></p>
          <%end%>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/share/_flatpickr.html.erb
<%= simple_form_for([bike, booking], data: { controller: 'flatpickr' }) do |f| %>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
   <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
   <%= f.submit 'Book', class: 'btn btn-primary' %>
 <% end %>

app/views/share/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Book a Bike 2023 <i class="fa-solid fa-person-biking"></i> @ Le Wagon
  </div>
</div>

app/views/share/_form.html.erb
<%= simple_form_for(@bike) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :bike_type, :collection => %w[Electric Road Mountain Folding Kids Hybrid City Trike] %>
  <%= f.input :price %>
  <%= f.input :bike_postcode2, label: 'Postcode' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/share/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "book-bike-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <a class="btn btn-outline-light my-2 my-sm-0 ms-2" href="/bikes/new">Add Bike</a>
          </li>
          <li class="nav-item">

          </li>
          <li class="nav-item dropdown">
            <%= image_tag "otis.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "View Booked Bikes", checkout_path, class: "dropdown-item" %>
              <%= link_to "Log out", "/users/sign_out", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <a class="btn btn-outline-light my-2 my-sm-0 ms-2" href="/users/sign_up">Add Bike</a>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/share/_review_form.erb
<%= simple_form_for [@bike, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content%>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/share/_search.html.erb
<div class="container flex">
  <div class="row">
    <% bike_type = %w(electric road mountain folding kids hybrid city trike)%>
    <% bike_type.each do |type| %>
    <div class="col text-center">
      <button type="button" class="btn btn-light"><%=type.capitalize%></div></button>
    <% end %>
  </div>
</div>


<%# <a class="d-block text-body-emphasis text-decoration-none" href="/icons/bicycle/"> %>
<%# <div class="px-3 py-4 mb-2 bg-body-secondary text-center rounded"> %>
<%# <i class="bi bi-bicycle"></i> %>
<%# </div> %>
<%# <div class="name text-muted text-decoration-none text-center pt-1">bicycle</div> %>
<%# </a> %>

app/views/share/_simplecal.html.erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>